name = "SFRPMicroMechanics"
uuid = "85b1d378-0dff-4863-a11e-e07702869b2f"
version = "0.1.0"
authors = ["barabule <werner.zanzinger@gmail.com>"]

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
GLMakie = "0.13.8"
GeometryBasics = "0.5.10"
LinearAlgebra = "1.12.0"
Random = "1.11.0"
StaticArrays = "1.9.16"
Statistics = "1.11.1"
